apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: ci-cd-app
    component: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
---
