apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: ci-cd-app
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30375  # You can use any free port in the range 30000-32767
  type: NodePort
