apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: ci-cd-app
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cd-app
      component: frontend
  template:
    metadata:
      labels:
        app: ci-cd-app
        component: frontend
    spec:
      containers:
        - name: frontend
          image: us.icr.io/ci-cd-app/ci-cd-app-frontend:latest  # Ensure this matches your image in IBM Cloud Registry
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
      imagePullSecrets:
        - name: ibm-cloud-registry-secret  # Reference the created secret to pull the image
